version: "3.9"

services:
  backend:
    build: ./backend
    container_name: plm-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/personal-library-management
      - REDIS_URL=redis://redis:6380

  mongo:
    image: mongo:6
    container_name: personal-library-management
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: plm-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
